# Generated by Django 5.2.7 on 2025-12-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_id',
            field=models.CharField(blank=True, help_text='ID платежа в Stripe', max_length=250),
        ),
    ]
