# Generated by Django 5.2.7 on 2026-01-04 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_session_id',
            field=models.CharField(blank=True, help_text='ID сессии Stripe Checkout', max_length=250),
        ),
    ]
